apiVersion: v1
kind: Service
metadata:
  name: besu-orion1
  labels:
    app: orion1
  namespace: besu
spec:
  type: ClusterIP
  selector:
    app: orion1
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: nodeport
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: clientport
