
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: validator1-sa
  namespace: besu

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: validator1-key-read-role
  namespace: besu
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [ besu-validator1-key ]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: validator1-rb
  namespace: besu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: validator1-key-read-role
subjects:
  - kind: ServiceAccount
    name: validator1-sa
    namespace: besu

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: validator1
  labels:
    app: validator1
  namespace: besu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator1
  serviceName: besu-validator1
  template:
    metadata:
      labels:
        app: validator1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: validator1-sa
      containers:
        - name: validator1
          image: hyperledger/besu:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VALIDATOR1_PUBKEY
              valueFrom:
                configMapKeyRef:
                  name: besu-configmap
                  key: validator1PubKey
            - name: NODES_HTTP_CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: besu-configmap
                  key: nodesHttpCorsOrigins
            - name: NODES_HOST_WHITELIST
              valueFrom:
                configMapKeyRef:
                  name: besu-configmap
                  key: nodesHostWhitelist
          volumeMounts:
            - name: key
              mountPath: /secrets
              readOnly: true
            - name: genesis-config
              mountPath: /configs
              readOnly: true
          ports:
            - containerPort: 8545
              name: json-rpc
              protocol: TCP
            - containerPort: 8546
              name: ws
              protocol: TCP
            - containerPort: 8547
              name: graphql
              protocol: TCP
            - containerPort: 30303
              name: rlpx
              protocol: TCP
            - containerPort: 30303
              name: discovery
              protocol: UDP
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec /opt/besu/bin/besu \
              --genesis-file=/configs/genesis.json \
              --node-private-key-file=/secrets/key \
              --rpc-http-enabled \
              --rpc-http-host=0.0.0.0 \
              --rpc-http-port=8545 \
              --rpc-http-cors-origins=${NODES_HTTP_CORS_ORIGINS} \
              --rpc-http-api=ETH,NET,IBFT \
              --graphql-http-enabled \
              --graphql-http-host=0.0.0.0 \
              --graphql-http-port=8547 \
              --graphql-http-cors-origins=${NODES_HTTP_CORS_ORIGINS} \
              --rpc-ws-enabled \
              --rpc-ws-host=0.0.0.0 \
              --rpc-ws-port=8546 \
              --metrics-enabled=true \
              --metrics-host=0.0.0.0 \
              --metrics-port=9545 \
              --host-whitelist=${NODES_HOST_WHITELIST} \
              --bootnodes=enode://${VALIDATOR1_PUBKEY}@${BESU_VALIDATOR1_SERVICE_HOST}:30303
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8545
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: key
          secret:
            secretName: besu-validator1-key
        - name: genesis-config
          configMap:
            name: besu-configmap
            items:
              - key: genesis.json
                path: genesis.json