---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "besu.fullname" . }}-bootnodes-init
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace.members }}
  namespace: {{ .Values.namespace.members }}
data:
  bootnodes-init.sh: |
    #!/bin/sh
    echo "VALIDATOR1_SERVICE_HOST=`getent hosts {{ template "besu.fullname" . }}-validator1.{{ .Values.namespace.consortium }}.svc.cluster.local | awk '{ print $1 }'`" > /bootnodes/service_data.sh
    echo "VALIDATOR2_SERVICE_HOST=`getent hosts {{ template "besu.fullname" . }}-validator2.{{ .Values.namespace.consortium }}.svc.cluster.local | awk '{ print $1 }'`" >> /bootnodes/service_data.sh
    source /bootnodes/service_data.sh && curl -X GET --connect-timeout 30 --max-time 10 --retry 6 --retry-delay 0 --retry-max-time 300 $VALIDATOR1_SERVICE_HOST:8545/liveness
