---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.consortium }}
  labels:
    app: {{ template "besu.fullname" . }}-consortium-namespace
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace.consortium }}
