{{- $nodeNumber := "node2" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "besu.fullname" . }}-{{ $nodeNumber }}privacy
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    component: {{ $nodeNumber }}privacy
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace.members }}
  namespace: {{ .Values.namespace.members }}
spec:
  replicas: {{ .Values.node.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "besu.name" . }}
      release: {{ .Release.Name }}
      component: {{ $nodeNumber }}privacy
  serviceName: "{{ $nodeNumber }}privacy-service"
  template:
    metadata:
      labels:
        app: {{ template "besu.name" . }}
        release: {{ .Release.Name }}
        component: {{ $nodeNumber }}privacy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
        - name: init-bootnode
          image: pegasyseng/k8s-helper:v1.18.4
          env:
            - name: VALIDATOR1_SERVICE_HOST
              value: "$({{ template "besu.upperfullname" . }}_VALIDATOR1_SERVICE_HOST)"
          volumeMounts:
            - name: bootnodes-init
              mountPath: /scripts/bootnodes-init.sh
              subPath: bootnodes-init.sh
            - name: bootnodes-services
              mountPath: /bootnodes
          command:
            - sh
            - -c
            - /scripts/bootnodes-init.sh
      containers:
        - name: {{ $nodeNumber }}privacy
          image: {{ .Values.image.besu.repository }}:{{ .Values.image.besu.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: "{{ .Values.node.cpuRequest }}"
              memory: "{{ .Values.node.memRequest }}"
            limits:
              cpu: "{{ .Values.node.cpuLimit }}"
              memory: "{{ .Values.node.memLimit }}"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VALIDATOR1_PUBKEY
              valueFrom:
                configMapKeyRef:
                  name: {{ template "besu.fullname" . }}-validators-configmap
                  key: validator1PubKey
            - name: VALIDATOR2_PUBKEY
              valueFrom:
                configMapKeyRef:
                  name: {{ template "besu.fullname" . }}-validators-configmap
                  key: validator2PubKey
            - name: VALIDATOR1_SERVICE_HOST
              value: "$({{ template "besu.upperfullname" . }}_VALIDATOR1_SERVICE_HOST)"
            - name: VALIDATOR2_SERVICE_HOST
              value: "$({{ template "besu.upperfullname" . }}_VALIDATOR2_SERVICE_HOST)"
            - name: ORION2_SERVICE_HOST
              value: "$({{ template "besu.upperfullname" . }}_ORION2_SERVICE_HOST)"
            # this allows us to pass in the orion service at runtime and make the script generic
            - name: BESU_ORION_SERVICE_HOST
              value: "$(ORION2_SERVICE_HOST)"
          volumeMounts:
            - name: orion-pubkey
              mountPath: /configs/orion
              readOnly: true
            - name: genesis-config
              mountPath: /etc/genesis
              readOnly: true
            - name: bootnodes-services
              mountPath: /bootnodes
              readOnly: true
            - name: nodes-init
              mountPath: /scripts/nodes-init.sh
              subPath: nodes-init.sh
            - name: config-toml
              mountPath: /etc/besu
              readOnly: true
            - name: data
              mountPath: /data
          ports:
            - name: json-rpc
              containerPort: {{ .Values.besuConfig.rpc.port }}
              protocol: TCP
            - name: ws
              containerPort: {{ .Values.besuConfig.ws.port }}
              protocol: TCP
            - name: graphql
              containerPort: {{ .Values.besuConfig.graphql.port }}
              protocol: TCP
            - name: rlpx
              containerPort: {{ .Values.besuConfig.p2p.port }}
              protocol: TCP
            - name: discovery
              containerPort: {{ .Values.besuConfig.p2p.port }}
              protocol: UDP
            - name: metrics
              containerPort: {{ .Values.besuConfig.metrics.port }}
              protocol: TCP
          command:
            - /bin/sh
            - -c
            - /scripts/nodes-init.sh
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8545
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8545
            initialDelaySeconds: 120
            periodSeconds: 30                     
      volumes:
        - name: genesis-config
          configMap:
            name: {{ template "besu.fullname" . }}-genesis-configmap
            items:
              - key: genesis.json
                path: genesis.json
        - name: orion-pubkey
          configMap:
            name: {{ template "besu.fullname" . }}-orion-configmap
            items:
              - key: orion2PubKey
                path: orion.pub
        - name: config-toml
          configMap:
            name: {{ template "besu.fullname" . }}-config-toml-configmap
        - name: data
          emptyDir:
            sizeLimit: "{{ .Values.node.pvcSizeLimit }}"
        # use a shared volume here to get the bootnode service ips for the enodes
        - name: bootnodes-services
          emptyDir: {}
        - name: bootnodes-init
          configMap:
            name: {{ template "besu.fullname" . }}-bootnodes-init
            defaultMode: 0777
        # source the ips from above in the shared volume as well as the orion service host and start besu
        - name: nodes-init
          configMap:
            name: {{ template "besu.fullname" . }}-nodes-privacy-init
            defaultMode: 0777
