
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "besu.fullname" . }}-nodes-privacy-init
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace.members }}
  namespace: {{ .Values.namespace.members }}
data:
  nodes-init.sh: |
    #!/bin/bash
    source /bootnodes/service_data.sh && /opt/besu/bin/besu \
     --config-file=/etc/besu/config.toml \
     --privacy-enabled=true \
     --privacy-public-key-file=/configs/orion/orion.pub \
     --privacy-url=http://${BESU_ORION_SERVICE_HOST}:8888 \
     --bootnodes=enode://${VALIDATOR1_PUBKEY}@${VALIDATOR1_SERVICE_HOST}:30303,enode://${VALIDATOR2_PUBKEY}@${VALIDATOR2_SERVICE_HOST}:30303
