apiVersion: v1
kind: ConfigMap
metadata:
  name: orion-configmap
  labels:
    app: orion-configmap
  namespace: besu
data:
  orion1PubKey: "Q7U40nEBpSg4AmieAKZ+4CB8wteH6eE57EDqOH34DRc="
  orion2PubKey: "SratFoTK6Nh0206JeeuOP6FSZ/m5I0LBm00flpTqmQE="
  orion.conf: |-
    nodeport = 8080
    nodenetworkinterface = "0.0.0.0"
    clientport = 8888
    clientnetworkinterface = "0.0.0.0"
    publickeys = ["/configs/keys/orion.pub"]
    privatekeys = ["/secrets/key"]
    passwords = "/secrets/password"
    tls = "off"

