apiVersion: v1
kind: Secret
metadata:
  name: besu-orion1-key
  labels:
    app: orion-keys
  namespace: besu
type: Opaque
stringData:
  key: |-
    {"data":{"bytes":"vgVJorMc9ybDq8OnuQVhtMr6IKNebUXlN2l7OS9uJWxpcUkFmDjfdmTlMqMdXSXE+udE/nUldZ/wjomk+1g4w5nX4aB+hzA3"},"type":"sodium-encrypted"}
  password: |-
    Password1
