apiVersion: v1
kind: Secret
metadata:
  name: {{ template "besu.fullname" . }}-orion2-key-secret
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{ (.Files.Glob "orion2.key").AsSecrets | indent 2 }}
{{ (.Files.Glob "orion2.password").AsSecrets | indent 2 }}
