{{- $orionNumber := "orion2" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "besu.fullname" . }}-{{ $orionNumber }}
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    component: {{ $orionNumber }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "besu.name" . }}
    release: {{ .Release.Name }}
    component: {{ $orionNumber }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: nodeport
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: clientport