apiVersion: apps/v1
kind: Deployment
metadata:
  name: besu-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: besu-operator
  template:
    metadata:
      labels:
        name: besu-operator
    spec:
      serviceAccountName: besu-operator
      containers:
        - name: besu-operator
          image: hyperledgerbesu/operators:v1alpha1
          command:
          - besu-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "besu-operator"
